version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: helphome
    environment:
      POSTGRES_USER: dingodave
      POSTGRES_PASSWORD: Kek3beg9!
      POSTGRES_DB: ihelphome
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: homerun-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/homerun_network
      SPRING_DATASOURCE_USERNAME: dingodave
      SPRING_DATASOURCE_PASSWORD: Kek3beg9!
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}

volumes:
  postgres_data:
